const counterActionTypes = {
    ON_INCREMENT: "ON_INCREMENT",
    ON_DECREMENT: "ON_DECREMENT",
    ON_ASYNC_ADDITION_REQUEST: "ON_ASYNC_ADDITION_REQUEST",
    ON_ASYNC_ADDITION_RESPONSE: "ON_ASYNC_ADDITION_RESPONSE",
    ON_ASYNC_ADDITION_WITH_LOADER_SUCCESS_REQUEST: "ON_ASYNC_ADDITION_WITH_LOADER_SUCCESS_REQUEST",
    ON_ASYNC_ADDITION_WITH_LOADER_SUCCESS_RESPONSE: "ON_ASYNC_ADDITION_WITH_LOADER_SUCCESS_RESPONSE",
    ON_ASYNC_SUBSTRACTION_REQUEST: "ON_ASYNC_SUBSTRACTION_REQUEST",
    ON_ASYNC_SUBSTRACTION_RESPONSE: "ON_ASYNC_SUBSTRACTION_RESPONSE",
}

export default counterActionTypes;